[float]
= An Approach for Efficient Code Reviews

== Benefits of Code Reviews

Code reviews are awesome, they are an absolute must have for any collective developing software together.
Aside from the obvious purpose of catching bugs, they also have many other benefits:

* They give a chance for everyone to share their knowledge.

* They open up a way for new developers to be mentored while working at their own pace.

* They create a step for a developer to review all their own work as well.

* They create homogeneity in the code in terms of style.

* They increase accountability so no code is the sole responsibility of one person.

== Code Review Hurdles

With all the benefits that codereviews bring, excellent code reviews are tricky to conduct in practice.
There's a number of hurdles to conducting thorough code reviews:

* A valuable code review can take a significant amount of time to do.

* Sometimes code changes are massive and extremely daunting to lay eyes on.

* It could be written in a way that really doesn't make sense to you.

* And sometimes, the intent of the code just doesn't make any sense.

From the perspective of the author, there are many ways to overcome these hurdles or just make reviews easier in general.
This includes  incremental pull requests, static code analysis, continuous integration, and so on.
But I want to focus efficient code reviewers from the perspective of the reviewer, how can a reviewer help themselves conduct a code review efficiently?

== A Time Saving Process

From reviewing code in a completely amateur environment (a University Team) and in an industry environment, I've learned to conduct my code reviews incrementally in a few steps:

. Does the intent of the changes make sense in the first place? If we're talking agile, do the changes match the story?

. Structurally, in terms of code architecture, is the code where it should be? Will it be maintainable?

. Are there any bugs or glitches?
This is a good step to actually run the changes.
Finding logical errors I also find are the most mentally taxing part of a code review, extra care should be take at this step.

. For the last step, is the coding style sound?
Does the code conform to the style of the rest of the project?

These steps help save time by hitting the biggest overarching changes first.
For example, as a reviewer, if the intent of the changes are misguided in the first place, then it's no longer necessary to carefully read every line in the diff.
It's also useful as a requester; it can be quite frusturating to address a number of small issues brought up in a code review just to have them all become obsolete by a larger issue brought up later.
It's tempting to comment on style/cosmetic issues first because they're the least mentally taxing to find, but there's a chance that those changes will become outdated when addressing a larger issue anyways.

Mentally, these steps also help break up a code review into more manageable pieces before having to carefully read every line.
If I'm crunched for time, I can comment on the first 2 points (or even just the first point) in the pull request first to let the author know it's on my radar, even if it's just a "Excited to see this change, looks good structurally! I'll give it a more in depth look later". Sometimes I'm just don't feel like reviewing code; with this I can push myself to just do the first step and often the others will easily follow, and if they don't at least I've responded to the author!

== Conclusion

Code reviews are an immeasurably beneficial asset for any software development team, but the cost they come at isn't negligible.
There are many ways to make code reviews more efficient with various automation tools, but at no cost, I think just coming into code review with a plan will also make code reviews more efficient.
I hope the advice I've shared helps you in your code reviews to be faster, friendlier, and more effective.


