[float]
= An Approach for Reviewing Code

[docdate]#Written by Enoch Tsang on August 4th, 2017#

Code reviews are awesome, they are an absolute must have for any group of people developing software together.
But from the perspective of the code reviewer, they are tricky to conduct in practice.
There are a number of hurdles to conducting thorough code reviews:

* A valuable code review can take a significant amount of time to do.

* Sometimes code changes are massive and extremely daunting to lay eyes on.

* The code could be written in a way that really doesn't make sense to you.

* And sometimes, the intent of the code just doesn't make any sense.

From the perspective of the author, there are many ways to overcome these hurdles or just make reviews easier in general.
This includes  incremental pull requests, static code analysis, continuous integration, and so on.
But I want to focus on efficient code reviews from the perspective of the reviewer, how can a reviewer help themselves conduct a code review efficiently?

== A Method for Reviewing Code

From reviewing code in a completely amateur environment (a University Team) and in an industry environment, I've formulated a method in approaching my code reviews. This means conducting code reviews incrementally in a few steps:

. Does the intent of the changes make sense in the first place? If we're talking agile, do the changes match the story?

. Structurally, in terms of code architecture, is the new code in the right files/directories? Will it be maintainable?

. Are there any bugs or glitches?
This is a good step to actually run the changes and/or review the logic behind accompanying unit tests.
Finding logical errors I find are the most mentally taxing part of a code review, extra care should be taken at this step.

. For the last step, is the coding style sound?
Does the code conform to the style of the rest of the project?

These steps help save time by hitting the biggest overarching changes first.
For example, as a reviewer, if the intent of the changes are misguided in the first place, then it's no longer necessary to carefully read every line in the diff.
It's also useful as a requester; it can be quite frusturating to address a number of small issues brought up in a code review just to have them all become obsolete by a larger issue brought up later.
It's tempting to comment on style/cosmetic issues first because they're the least mentally taxing to find, but there's a chance that those changes will become outdated when addressing a larger issue anyways.

Mentally, these steps also help break up a code review into more manageable pieces before having to carefully read every line.
If I'm crunched for time, I can comment on the first 2 points (or even just the first point) in the pull request first to let the author know it's on my radar, even if it's just a "Excited to see this change, looks good structurally! I'll give it a more in depth look later". Sometimes I just don't feel like reviewing code; with this I can push myself to just do the first step and often the others will easily follow, and if they don't at least I've responded to the author!

== Conclusion

Code reviews are an immeasurably beneficial asset for any software development team, but the cost they come at isn't negligible.
There are many ways to make code reviews more efficient with various automation tools, but at no cost, I think just coming into code review with a plan will also make code reviews more efficient.
I hope the advice I've shared helps you in your code reviews to be faster and more effective.
