[float]
= 15 Minute Meat Sauce Pasta

[docdate]#Written by Enoch Tsang on Nov 25th, 2024#

== Ingredients

* 1 lb Pasta
* 2 Medium Onions
* 2 Celery Stalks
* 2 Carrots
* 6 Garlic Cloves
* 2 Tbsp Olive Oil
* 1 lb Ground Beef
* 3 Tbsp Tomato Paste
* 1 Tbsp Dried Oregano
* 1 Tbsp Sugar
* 1 Tbsp Salt
* 1 Tsp Black Pepper
* ½ Cup Red Wine
* 1 (15-ounce) can tomato sauce
* 4 Tbsp cold unsalted butter

== Directions

. Cook pasta in a large pot of boiling salted water, stirring occasionally, until al dente; drain and transfer to a large bowl.
. Process Onion, celery, carrot, and garlic in a food processor until finely chopped.
. Heat oil in a large skillet over high and cook vegetables and beef, break up the beef with the spatula and stir.
. When the meat is beginning to brown, about 3 minutes, stir in tomato paste, oregano, salt, pepper, until heated through.
. Stir in the cook and stir until the wine is reduced, about 1 minute.
. Stir in the tomato sauce, reduce to medium and sauce until the desired thickness.
. Remove from heat and stir in the cutter.
. Toss meat sauce on pasta and enjoy!

=== Notes

Adapted from link:https://www.epicurious.com/recipes/food/views/pasta-with-15-minute-meat-sauce-56390063[Pasta With 15-Minute Meat Sauce by Anna Stockwell].

The pasta and meat sauce fridge well and can be saved as meal prep. This recipe prepares about 8 portions worth.
