[float]
= Korean Ground Beef Bulgogi Bowls

[docdate]#Written by Enoch Tsang on Nov 26th, 2024#

== Ingredients

* 2 lb Extra Lean Ground Beef
* 2 Large Onions
* 8 Garlic Cloves
* 6 Tbsp Soy Sauce (Not the low sodium kind)
* 5 Tbsp Sugar
* 1 Tbsp Mirin
* 1 Tbsp Sesame Oil
* Eggs
* 8 Cups Rice
* Green Onions

== Directions

. Cook the rice.
. Puree 1 Onion and dice the other one.
. Mince the garlic.
. Make the bulgogi sauce by mixing the pureed onion, garlic, soy sauce, sugar, mirin, and sesame oil.
. Marinate the beef by mixing the ground beef in the bulgogi sauce.
. Heat a wok or large skillet over medium heat, add a little oil and the diced onion. Cook until the onion is soft and translucent.
. Raise the heat to medium-high heat and add the marinated beef.
. Once about 3/4 of the juice is evaporated, remove half the beef.
. Cook the rest of the beef until it has taken on a lovely, caramel-brown color with crispy edges. Then mix this crispy beef with the slightly wet beef.
. Serve the bulgogi beef over rice and garnish with green onions and a fried egg on top.

=== Notes

Adapted from link:https://thesubversivetable.com/bulgogi-bowls/[Korean Ground Beef Bulgogi Bowls by Lis Lam].

The bulgogi reheats and stores well and can be saved as meal prep. This recipe prepares about 6 portions worth.
